// words.js - Word dictionary and puzzle generation utilities

// Curated word bank organized by length (3-10)
export const WORD_BANK = {
  3: [
    'ACE','ACT','ADD','AGE','AID','AIM','AIR','ALL','AND','ANT','APE','ARC','ARM','ART','ATE',
    'BAD','BAG','BAT','BAY','BED','BIG','BIT','BOW','BOX','BOY','BUG','BUS','BUY','CAN','CAP',
    'CAR','CAT','COP','CRY','CUB','CUP','CUT','DAD','DAY','DIG','DOG','DOT','DRY','DUE','EAR',
    'EAT','EGG','ELF','END','ERA','EVE','EYE','FAN','FAR','FAT','FEW','FIG','FIN','FIT','FLY',
    'FOG','FOR','FOX','FUN','FUR','GAP','GAS','GEM','GET','GOD','GUM','GUN','GUT','GYM','HAD',
    'HAM','HAS','HAT','HEN','HER','HID','HIM','HIT','HOG','HOP','HOT','HOW','HUB','HUG','HUT',
    'ICE','ILL','INK','INN','ION','IVY','JAM','JAR','JAW','JET','JOB','JOG','JOY','JUG','KEY',
    'KID','KIT','LAB','LAP','LAW','LAY','LED','LEG','LET','LID','LIT','LOG','LOT','LOW','MAD',
    'MAN','MAP','MAT','MAY','MEN','MET','MIX','MOB','MOM','MOP','MUD','MUG','NAP','NET','NEW',
    'NIT','NOD','NOR','NOT','NOW','NUN','NUT','OAK','OAR','ODD','OIL','OLD','ONE','OPT','ORE',
    'OUR','OUT','OWL','OWN','PAD','PAN','PAT','PAW','PAY','PEA','PEN','PET','PIE','PIG','PIN',
    'PIT','POD','POP','POT','PRY','PUB','PUN','PUP','PUT','RAG','RAM','RAN','RAT','RAW','RAY',
    'RED','RIB','RIG','RIM','RIP','ROB','ROD','ROT','ROW','RUB','RUG','RUN','RYE','SAD','SAP',
    'SAT','SAW','SAY','SEA','SET','SEW','SHE','SHY','SIN','SIP','SIT','SIX','SKI','SKY','SLY',
    'SOB','SON','SOP','SOW','SPY','STY','SUB','SUM','SUN','TAB','TAN','TAP','TAR','TAX','TEA',
    'TEN','THE','TIE','TIN','TIP','TOE','TON','TOO','TOP','TOW','TOY','TRY','TUB','TUG','TWO',
    'URN','USE','VAN','VAT','VET','VIA','VOW','WAR','WAX','WAY','WEB','WET','WHO','WHY','WIG',
    'WIN','WIT','WOE','WOK','WON','WOO','WOW','YAK','YAM','YAP','YES','YET','YEW','YOU','ZAP',
    'ZEN','ZIP','ZOO'
  ],
  4: [
    'ABLE','ARCH','ARMY','BACK','BAKE','BALL','BAND','BANK','BARK','BARN','BASE','BATH','BEAM',
    'BEAR','BEAT','BELL','BELT','BEND','BEST','BIKE','BIRD','BITE','BLOW','BLUE','BOAT','BODY',
    'BOLT','BOMB','BOND','BONE','BOOK','BOOT','BORN','BOWL','BULK','BURN','CAGE','CAKE','CALL',
    'CALM','CAME','CAMP','CARD','CARE','CART','CASE','CASH','CAST','CAVE','CHIP','CITY','CLAP',
    'CLAY','CLIP','CLUB','CLUE','COAL','COAT','CODE','COIN','COLD','COME','COOK','COOL','COPE',
    'COPY','CORD','CORE','CORN','COST','CREW','CROP','CURE','CURL','CUTE','DARE','DARK','DATA',
    'DATE','DAWN','DEAD','DEAL','DEAR','DECK','DEEP','DEER','DESK','DIAL','DICE','DIET','DIRT',
    'DISH','DOCK','DOES','DONE','DOOR','DOSE','DOWN','DRAG','DRAW','DROP','DRUM','DUAL','DULL',
    'DUNE','DUST','DUTY','EACH','EARN','EASE','EAST','EASY','EDGE','EDIT','FACE','FACT','FADE',
    'FAIL','FAIR','FAKE','FALL','FAME','FARM','FAST','FATE','FEAR','FEED','FEEL','FELL','FILE',
    'FILL','FILM','FIND','FINE','FIRE','FIRM','FISH','FLAG','FLAT','FLEW','FLIP','FLOW','FOAM',
    'FOLD','FOLK','FOND','FONT','FOOD','FOOL','FOOT','FORK','FORM','FORT','FOUL','FOUR','FREE',
    'FROM','FUEL','FULL','FUND','FUSE','GAIN','GALE','GAME','GANG','GATE','GAVE','GAZE','GEAR',
    'GENE','GIFT','GIRL','GIVE','GLAD','GLOW','GLUE','GOAL','GOAT','GOES','GOLD','GOLF','GONE',
    'GOOD','GRAB','GRAY','GREW','GRID','GRIM','GRIN','GRIP','GROW','GULF','HACK','HAIR','HALF',
    'HALL','HALT','HAND','HANG','HARD','HARM','HATE','HAVE','HEAD','HEAL','HEAP','HEAR','HEAT',
    'HEEL','HELD','HELP','HERE','HERO','HIGH','HIKE','HILL','HINT','HIRE','HOLD','HOLE','HOME',
    'HOOK','HOPE','HORN','HOST','HOUR','HUGE','HUNG','HUNT','HURT','HYMN','ICON','IDEA','INCH',
    'INTO','IRON','ISLE','ITEM','JACK','JAIL','JAZZ','JERK','JOKE','JUMP','JURY','JUST','KEEN',
    'KEEP','KEPT','KICK','KIDS','KILL','KIND','KING','KISS','KNEE','KNEW','KNIT','KNOB','KNOT',
    'KNOW','LACK','LAID','LAKE','LAMP','LAND','LANE','LAST','LATE','LAWN','LEAD','LEAF','LEAN',
    'LEAP','LEFT','LEND','LENS','LESS','LIFE','LIFT','LIKE','LIMB','LIME','LINE','LINK','LION',
    'LIST','LIVE','LOAD','LOAN','LOCK','LOFT','LOGO','LONE','LONG','LOOK','LORD','LOSE','LOSS',
    'LOST','LOVE','LUCK','LUMP','LUNG','MADE','MAIL','MAIN','MAKE','MALE','MALL','MANY','MARK',
    'MASK','MASS','MATE','MAZE','MEAL','MEAN','MEAT','MEET','MELT','MENU','MERE','MESH','MILD',
    'MILE','MILK','MILL','MIND','MINE','MINT','MISS','MODE','MOLD','MOOD','MOON','MORE','MOSS',
    'MOST','MOTH','MOVE','MUCH','MUST','MYTH','NAIL','NAME','NAVY','NEAR','NEAT','NECK','NEED',
    'NEST','NEWS','NEXT','NICE','NINE','NODE','NONE','NORM','NOSE','NOTE','NOUN','ODDS','OKAY',
    'ONCE','ONLY','ONTO','OPEN','OVEN','OVER','PACE','PACK','PAGE','PAID','PAIN','PAIR','PALE',
    'PALM','PARK','PART','PASS','PAST','PATH','PEAK','PEEL','PEER','PICK','PILE','PINE','PINK',
    'PIPE','PLAN','PLAY','PLOT','PLUG','PLUM','PLUS','POEM','POET','POLL','POND','POOL','POOR',
    'PORK','PORT','POSE','POST','POUR','PRAY','PREY','PROP','PULL','PUMP','PURE','PUSH','QUIT',
    'QUIZ','RACE','RACK','RAGE','RAID','RAIL','RAIN','RANK','RARE','RATE','READ','REAL','REAR',
    'REED','REEL','RELY','RENT','REST','RICE','RICH','RIDE','RING','RIOT','RISE','RISK','ROAD',
    'ROAM','ROCK','RODE','ROLE','ROLL','ROOF','ROOM','ROOT','ROPE','ROSE','RUIN','RULE','RUSH',
    'RUST','SAFE','SAGE','SAID','SAIL','SAKE','SALE','SALT','SAME','SAND','SANG','SAVE','SCAN',
    'SEAL','SEED','SEEK','SEEM','SEEN','SELF','SELL','SEND','SENT','SHED','SHIN','SHIP','SHOE',
    'SHOP','SHOT','SHOW','SHUT','SICK','SIDE','SIGH','SIGN','SILK','SING','SINK','SITE','SIZE',
    'SKIP','SLAM','SLAP','SLID','SLIM','SLIP','SLOT','SLOW','SNAP','SNOW','SOAK','SOAP','SOAR',
    'SOCK','SOFA','SOFT','SOIL','SOLD','SOLE','SOME','SONG','SOON','SORT','SOUL','SOUR','SPAN',
    'SPIN','SPIT','SPOT','STAR','STAY','STEM','STEP','STEW','STOP','SUCH','SUIT','SUNG','SURE',
    'SURF','SWAN','SWAP','SWIM','TAIL','TAKE','TALE','TALK','TALL','TANK','TAPE','TASK','TAXI',
    'TEAM','TEAR','TELL','TEND','TENT','TERM','TEST','TEXT','THAN','THEM','THEN','THEY','THIN',
    'THIS','TICK','TIDE','TIDY','TIED','TIER','TILE','TILL','TILT','TIME','TINY','TIRE','TOAD',
    'TOLD','TOLL','TONE','TOOK','TOOL','TOPS','TORE','TORN','TOSS','TOUR','TOWN','TRAP','TRAY',
    'TREE','TREK','TRIM','TRIO','TRIP','TRUE','TUBE','TUCK','TUNA','TUNE','TURN','TWIN','TYPE',
    'UGLY','UNDO','UNIT','UPON','URGE','USED','USER','VALE','VARY','VAST','VERB','VERY','VICE',
    'VIEW','VINE','VISA','VOID','VOLT','VOTE','WADE','WAGE','WAIT','WAKE','WALK','WALL','WANT',
    'WARD','WARM','WARN','WARP','WASH','WAVE','WEAK','WEAR','WEED','WEEK','WELL','WENT','WEST',
    'WHAT','WHEN','WIDE','WIFE','WILD','WILL','WIND','WINE','WING','WIPE','WIRE','WISE','WISH',
    'WITH','WOKE','WOLF','WOOD','WOOL','WORD','WORE','WORK','WORM','WORN','WRAP','YARD','YARN',
    'YEAR','YELL','YOUR','ZEAL','ZERO','ZONE','ZOOM'
  ],
  5: [
    'ABOUT','ABOVE','ACTED','ADMIT','ADOPT','ADULT','AFTER','AGAIN','AGENT','AGREE','AHEAD',
    'ALARM','ALBUM','ALERT','ALIEN','ALIGN','ALIVE','ALLOW','ALONE','ALONG','ALTER','AMAZE',
    'ANGEL','ANGER','ANGLE','ANGRY','ANKLE','APART','APPLE','APPLY','ARENA','ARMOR','ASIDE',
    'ATLAS','AUDIO','AVOID','AWAKE','AWARD','BADGE','BASIC','BEACH','BEGIN','BEING','BELOW',
    'BENCH','BERRY','BLANK','BLAST','BLAZE','BLEND','BLIND','BLINK','BLOCK','BLOOD','BLOOM',
    'BOARD','BONUS','BOOTH','BOUND','BRAIN','BRAND','BRAVE','BREAD','BREAK','BRICK','BRIDE',
    'BRIEF','BRING','BROAD','BRUSH','BUILD','BUILT','BUNCH','BURST','CABIN','CABLE','CANDY',
    'CARRY','CATCH','CAUSE','CHAIN','CHAIR','CHARM','CHART','CHASE','CHEAP','CHECK','CHEEK',
    'CHEER','CHESS','CHEST','CHIEF','CHILD','CHUNK','CIVIL','CLAIM','CLASH','CLASS','CLEAN',
    'CLEAR','CLERK','CLICK','CLIFF','CLIMB','CLOCK','CLONE','CLOSE','CLOTH','CLOUD','COACH',
    'COAST','COLOR','COUNT','COURT','COVER','CRACK','CRAFT','CRANE','CRASH','CRAZY','CREAM',
    'CRIME','CROSS','CROWD','CROWN','CRUSH','CURVE','CYCLE','DANCE','DELAY','DEPTH','DEVIL',
    'DIRTY','DOUBT','DRAFT','DRAIN','DRAMA','DRAWN','DREAM','DRESS','DRIFT','DRINK','DRIVE',
    'DROVE','DYING','EAGER','EARLY','EARTH','EIGHT','ELECT','ELITE','EMPTY','ENEMY','ENJOY',
    'ENTER','EQUAL','ERROR','EVENT','EVERY','EXACT','EXIST','EXTRA','FAITH','FALSE','FEAST',
    'FENCE','FEWER','FIBER','FIELD','FIGHT','FINAL','FIRST','FLAME','FLASH','FLEET','FLESH',
    'FLOAT','FLOOD','FLOOR','FLOWN','FLUID','FLUSH','FOCUS','FORCE','FORGE','FORTH','FORUM',
    'FOUND','FRAME','FRAUD','FRESH','FRONT','FROST','FROZE','FRUIT','FUNNY','GHOST','GIANT',
    'GIVEN','GLASS','GLOBE','GLORY','GLOVE','GOING','GRACE','GRADE','GRAIN','GRAND','GRANT',
    'GRAPH','GRASP','GRASS','GRAVE','GREAT','GREEN','GREET','GRIEF','GRIND','GROUP','GROVE',
    'GROWN','GUARD','GUESS','GUEST','GUIDE','GUILT','HAPPY','HAVEN','HEART','HEAVY','HENCE',
    'HONEY','HONOR','HORSE','HOTEL','HOUSE','HUMAN','HUMOR','IDEAL','IMAGE','INDEX','INNER',
    'INPUT','IRONY','IVORY','ISSUE','JOINT','JOKER','JUDGE','JUICE','KNOCK','KNOWN','LABEL',
    'LARGE','LASER','LATER','LAUGH','LAYER','LEARN','LEASE','LEAST','LEAVE','LEGAL','LEMON',
    'LEVEL','LIGHT','LIMIT','LOCAL','LOGIC','LOOSE','LOVER','LOWER','LOYAL','LUCKY','LUNAR',
    'LUNCH','MAGIC','MAJOR','MAKER','MANOR','MAPLE','MARCH','MATCH','MAYOR','MEDIA','MERCY',
    'MERGE','MERIT','METAL','METER','MIGHT','MINOR','MINUS','MIXED','MODEL','MONEY','MONTH',
    'MORAL','MOTOR','MOUNT','MOUSE','MOUTH','MOVIE','MUSIC','NERVE','NEVER','NIGHT','NOBLE',
    'NOISE','NORTH','NOVEL','NURSE','OCEAN','OFFER','OFTEN','OLIVE','ONSET','OPERA','ORBIT',
    'ORDER','OTHER','OUTER','OWNER','PAINT','PANEL','PANIC','PAPER','PATCH','PAUSE','PEACE',
    'PEARL','PHASE','PHONE','PHOTO','PIANO','PIECE','PILOT','PITCH','PIZZA','PLACE','PLAIN',
    'PLANE','PLANT','PLATE','PLAZA','PLEAD','POINT','POLAR','POUND','POWER','PRESS','PRICE',
    'PRIDE','PRIME','PRINT','PRIOR','PRIZE','PROOF','PROUD','PROVE','PULSE','PUNCH','QUEEN',
    'QUERY','QUEST','QUEUE','QUICK','QUIET','QUITE','QUOTE','RADAR','RADIO','RAISE','RALLY',
    'RANCH','RANGE','RAPID','REACH','REACT','READY','REALM','REBEL','REIGN','RELAX','REPLY',
    'RIDER','RIDGE','RIFLE','RIGHT','RIGID','RIVAL','RIVER','ROBOT','ROUGH','ROUND','ROUTE',
    'ROYAL','RULER','RURAL','SAINT','SALAD','SAUCE','SCALE','SCARE','SCENE','SCOPE','SCORE',
    'SCOUT','SEDAN','SENSE','SERVE','SEVEN','SHALL','SHAME','SHAPE','SHARE','SHARK','SHARP',
    'SHEER','SHEET','SHELF','SHELL','SHIFT','SHIRT','SHOCK','SHORE','SHORT','SHOUT','SIGHT',
    'SINCE','SIXTH','SIXTY','SKILL','SKULL','SLICE','SLIDE','SLOPE','SMART','SMELL','SMILE',
    'SMOKE','SNAKE','SOLAR','SOLID','SOLVE','SOUTH','SPACE','SPARE','SPARK','SPEAK','SPEAR',
    'SPEED','SPELL','SPEND','SPENT','SPICE','SPINE','SPLIT','SPOKE','SPORT','SPRAY','SQUAD',
    'STACK','STAFF','STAGE','STAKE','STAIR','STALL','STAMP','STAND','STARE','START','STATE',
    'STEAK','STEAL','STEAM','STEEL','STEEP','STEER','STERN','STICK','STILL','STOCK','STOLE',
    'STONE','STOOD','STORE','STORM','STORY','STOVE','STRAP','STRAW','STRIP','STUCK','STUDY',
    'STUFF','STYLE','SUGAR','SUITE','SUNNY','SUPER','SURGE','SWAMP','SWEAR','SWEET','SWEPT',
    'SWIFT','SWING','SWORD','TABLE','TASTE','TEACH','TEETH','THEME','THICK','THIEF','THING',
    'THINK','THIRD','THOSE','THREE','THREW','THROW','THUMB','TIGER','TIGHT','TIMER','TIRED',
    'TITLE','TODAY','TOKEN','TOPIC','TOTAL','TOUCH','TOUGH','TOWEL','TOWER','TRACE','TRACK',
    'TRADE','TRAIL','TRAIN','TRAIT','TRASH','TREAT','TREND','TRIAL','TRIBE','TRICK','TRIED',
    'TRUCK','TRULY','TRUNK','TRUST','TRUTH','TWICE','TWIST','ULTRA','UNCLE','UNDER','UNION',
    'UNITE','UNITY','UNTIL','UPPER','UPSET','URBAN','USUAL','UTTER','VALID','VALUE','VAULT',
    'VERSE','VIDEO','VITAL','VIVID','VOCAL','VOICE','WAGON','WASTE','WATCH','WATER','WEAVE',
    'WEDGE','WEIRD','WHEAT','WHEEL','WHERE','WHICH','WHILE','WHITE','WHOLE','WHOSE','WIDER',
    'WITCH','WOMAN','WOMEN','WORLD','WORRY','WORSE','WORST','WORTH','WOULD','WOUND','WRATH',
    'WRITE','WRONG','WROTE','YACHT','YIELD','YOUNG','YOUTH','ZEBRA'
  ],
  6: [
    'ABSORB','ACCEPT','ACCESS','ACTION','ACTIVE','ACTUAL','ADJUST','ADVICE','AFFORD','AGENCY',
    'ALMOST','ALWAYS','AMOUNT','ANCHOR','ANIMAL','ANNUAL','ANSWER','APPEAL','APPEAR','ARCTIC',
    'ARTIST','ASSUME','ATTACH','ATTACK','AUGUST','AUTUMN','AVENUE','BARELY','BARREL','BASKET',
    'BATTLE','BECOME','BEFORE','BEHALF','BEHIND','BELONG','BESIDE','BEYOND','BISHOP','BLANKS',
    'BORDER','BORROW','BOTTLE','BOTTOM','BOUNCE','BRANCH','BREATH','BRIDGE','BRIGHT','BROKEN',
    'BRONZE','BROWSE','BUBBLE','BUCKET','BUDGET','BUNDLE','BUREAU','BUTTER','BUTTON','CAMERA',
    'CANCEL','CANDLE','CAREER','CASTLE','CASUAL','CAUGHT','CENTER','CHANCE','CHANGE','CHARGE',
    'CHEESE','CHURCH','CIRCLE','CLIENT','CLOSET','COFFEE','COLUMN','COMBAT','COMEDY','COMING',
    'COMMON','CONVEY','COOKIE','CORNER','COSTLY','COTTON','COUNTY','COUPLE','COURSE','COUSIN',
    'CREATE','CREDIT','CRISIS','CUSTOM','DAMAGE','DANGER','DARING','DEALER','DEBATE','DECADE',
    'DECENT','DEFEAT','DEFEND','DEFINE','DEGREE','DEMAND','DESERT','DESIGN','DESIRE','DETAIL',
    'DETECT','DEVICE','DINING','DIRECT','DOMAIN','DOUBLE','DOZENS','DRAGON','DRIVER','EASILY',
    'EDITOR','EFFECT','EFFORT','EIGHTH','EITHER','EMERGE','EMPIRE','ENABLE','ENDURE','ENERGY',
    'ENGAGE','ENGINE','ENOUGH','ENSURE','ENTIRE','ENTITY','EQUITY','ESCAPE','ESTATE','EVOLVE',
    'EXCEED','EXCEPT','EXCUSE','EXPAND','EXPECT','EXPERT','EXPORT','EXPOSE','EXTENT','FABRIC',
    'FAIRLY','FALLEN','FAMILY','FAMOUS','FARMER','FATHER','FELLOW','FEMALE','FIGURE','FILTER',
    'FINGER','FINISH','FISCAL','FLAVOR','FLIGHT','FOLLOW','FOREST','FORGET','FORMAL','FORMAT',
    'FORMER','FOSSIL','FOUGHT','FOURTH','FREEZE','FRIEND','FROZEN','FUTURE','GAINED','GALAXY',
    'GARDEN','GATHER','GENDER','GENIUS','GENTLE','GLOBAL','GOLDEN','GOVERN','GROWTH','GUITAR',
    'HANDLE','HAPPEN','HARDLY','HAZARD','HEADER','HEALTH','HEAVEN','HEIGHT','HIDDEN','HIGHLY',
    'HOLDER','HONEST','HORROR','HUNGER','HUNTER','IGNORE','IMPACT','IMPORT','IMPOSE','INCOME',
    'INDEED','INDOOR','INFANT','INFORM','INJURY','INSERT','INSIDE','INSIST','INTACT','INTEND',
    'INTENT','INVEST','ISLAND','ITSELF','JACKET','JERSEY','JUNGLE','JUNIOR','KEEPER','KIDNEY',
    'KNIGHT','LATEST','LATTER','LAUNCH','LAWYER','LAYOUT','LEADER','LEAGUE','LEGACY','LENGTH',
    'LESSON','LETTER','LIKELY','LINEAR','LIQUID','LISTEN','LITTLE','LIVELY','LIVING','LOCATE',
    'LONELY','LOVELY','LUXURY','MAINLY','MANAGE','MANNER','MANUAL','MARBLE','MARGIN','MARINE',
    'MARKER','MARKET','MASTER','MATTER','MEDIUM','MEMBER','MEMORY','MENTAL','MENTOR','METHOD',
    'MIDDLE','MIGHTY','MINDED','MIRROR','MOBILE','MODERN','MODEST','MODULE','MOMENT','MOTIVE',
    'MUSEUM','MUTUAL','MYSELF','NARROW','NATION','NATIVE','NATURE','NEARBY','NEARLY','NEEDLE',
    'NOBODY','NORMAL','NOTICE','NOTION','NUMBER','OBJECT','OBTAIN','OCCUPY','OFFEND','OFFICE',
    'OFFSET','ONLINE','OPENER','OPPOSE','OPTION','ORANGE','ORIENT','ORIGIN','OUTFIT','OUTPUT',
    'OXYGEN','PACKED','PALACE','PARENT','PARISH','PARTLY','PATROL','PATRON','PEANUT','PENCIL',
    'PEOPLE','PEPPER','PERIOD','PERMIT','PERSON','PHRASE','PILLAR','PLANET','PLAYER','PLEASE',
    'PLENTY','PLUNGE','POCKET','POETRY','POISON','POLICY','POLISH','POLITE','PORTAL','POSTER',
    'POTATO','POWDER','PRAISE','PRAYER','PREFIX','PRETTY','PRINCE','PRISON','PROFIT','PROMPT',
    'PROPER','PROVEN','PUBLIC','PURSUE','PUZZLE','RABBIT','RACIAL','RANDOM','RANGER','RARELY',
    'RATING','RATHER','READER','REALLY','REASON','RECALL','RECENT','RECORD','REDUCE','REFORM',
    'REFUSE','REGARD','REGIME','REGION','REGRET','REJECT','RELATE','RELIEF','REMAIN','REMEDY',
    'REMOTE','REMOVE','RENDER','RENTAL','REPAIR','REPEAT','REPORT','RESCUE','RESIGN','RESIST',
    'RESORT','RESULT','RETAIL','RETAIN','RETIRE','RETURN','REVEAL','REVIEW','REVISE','REVOLT',
    'REWARD','RHYTHM','RIDING','RISING','RITUAL','ROBUST','ROCKET','ROLLER','RUBBER','RULING',
    'RUNNER','SAFETY','SALARY','SAMPLE','SAVING','SCARED','SCHEME','SCHOOL','SCREEN','SCRIPT',
    'SEARCH','SEASON','SECOND','SECRET','SECTOR','SECURE','SELECT','SENIOR','SERIAL','SERIES',
    'SERVER','SETTLE','SEVERE','SHADOW','SHIELD','SIGNAL','SILENT','SILVER','SIMPLE','SIMPLY',
    'SINGER','SINGLE','SISTER','SKETCH','SLIGHT','SLOWLY','SMOOTH','SOCCER','SOCIAL','SOCKET',
    'SOFTLY','SOLELY','SOUGHT','SOURCE','SPEECH','SPHERE','SPIRIT','SPLASH','SPREAD','SPRING',
    'SQUARE','STABLE','STANCE','STATUE','STATUS','STEADY','STOLEN','STRAIN','STRAND','STREAK',
    'STREAM','STREET','STRESS','STRICT','STRIDE','STRIKE','STRING','STROKE','STRONG','STRUCK',
    'STUDIO','SUBMIT','SUDDEN','SUFFER','SUMMIT','SUPPLY','SURELY','SURVEY','SWITCH','SYMBOL',
    'SYSTEM','TACKLE','TALENT','TARGET','TEMPLE','TENANT','TENDER','TENNIS','TERROR','THANKS',
    'THIRTY','THOUGH','THREAD','THREAT','THRIVE','THRONE','TIMBER','TISSUE','TONGUE','TOWARD',
    'TRAVEL','TREATY','TRIBAL','TROPHY','TUNNEL','TWELVE','TWENTY','UNFAIR','UNIQUE','UNITED',
    'UNLESS','UNLIKE','UNLOCK','UNSAFE','UPDATE','UPHOLD','USEFUL','VALLEY','VARIED','VENDOR',
    'VERIFY','VICTIM','VIEWER','VIRGIN','VIRTUE','VISION','VISUAL','VOLUME','WANDER','WARMLY',
    'WEAPON','WEEKLY','WEIGHT','WIDELY','WICKED','WINDOW','WINNER','WINTER','WISDOM','WITHIN',
    'WONDER','WOODEN','WORKER','WORTHY','WRITER','YEARLY','YELLOW','ZENITH','ZODIAC'
  ],
  7: [
    'ABILITY','ABSENCE','ACADEMY','ACCOUNT','ACHIEVE','ACQUIRE','ADDRESS','ADVANCE','AIRPORT',
    'ALREADY','AMAZING','ANCIENT','ANGULAR','ANXIETY','ANYTIME','APPLIED','ARTICLE','ATTRACT',
    'AUCTION','BALANCE','BANKING','BARGAIN','BARRIER','BATTERY','BEARING','BECAUSE','BEDROOM',
    'BELIEVE','BENEFIT','BESIDES','BILLION','BLANKET','BLOSSOM','BRACKET','BREADTH','BREATHE',
    'BROTHER','BROUGHT','BROWSER','BUFFALO','BUILDER','BURNING','CABINET','CAPABLE','CAPITAL',
    'CAPTAIN','CAPTURE','CAREFUL','CATALOG','CAUTION','CEILING','CENTRAL','CERTAIN','CHAMBER',
    'CHANNEL','CHAPTER','CHARITY','CHICKEN','CHRONIC','CIRCUIT','CITIZEN','CLASSIC','CLIMATE',
    'CLOSEST','CLOSING','CLUSTER','COASTAL','COLLEGE','COMBINE','COMFORT','COMMAND','COMMENT',
    'COMPACT','COMPANY','COMPARE','COMPASS','COMPETE','COMPLEX','CONCEPT','CONCERN','CONDUCT',
    'CONFIRM','CONNECT','CONSENT','CONSIST','CONTACT','CONTAIN','CONTENT','CONTEST','CONTEXT',
    'CONTROL','CONVERT','COOKING','CORRECT','COUNCIL','COUNTER','COUNTRY','COURAGE','CREATED',
    'CREATOR','CRICKET','CRYSTAL','CULTURE','CURRENT','CUSTOMS','CUTTING','DAMAGED','DEALING',
    'DECIMAL','DECLARE','DECLINE','DEFAULT','DELIVER','DENSITY','DEPOSIT','DESERVE','DESKTOP',
    'DESPITE','DESTROY','DEVELOP','DEVOTED','DIGITAL','DISCUSS','DISEASE','DISMISS','DISPLAY',
    'DISPOSE','DISPUTE','DISTANT','DYNAMIC','ECONOMY','EDITION','ELDERLY','ELEMENT','EMOTION',
    'ENDLESS','ENHANCE','EPISODE','ESSENCE','ETERNAL','EXAMINE','EXAMPLE','EXCITED','EXECUTE',
    'EXHIBIT','EXPENSE','EXPLOIT','EXPLORE','EXPRESS','EXTRACT','EXTREME','FACULTY','FAILURE',
    'FANTASY','FARMING','FASHION','FEATURE','FICTION','FIFTEEN','FINANCE','FINDING','FITNESS',
    'FOREIGN','FOREVER','FORMULA','FORTUNE','FORWARD','FOUNDER','FREEDOM','FULFILL','FUNDING',
    'FURTHER','GALLERY','GATEWAY','GENERAL','GENETIC','GENUINE','GLIMPSE','GRADUAL','GRAMMAR',
    'GRANITE','GRAPHIC','GRAVITY','GREATLY','HABITAT','HANDFUL','HAPPILY','HARBOUR','HARVEST',
    'HEADING','HEALTHY','HEARING','HEATING','HEAVILY','HELPFUL','HIGHWAY','HIMSELF','HISTORY',
    'HOLIDAY','HORIZON','HOSTILE','HOUSING','HOWEVER','HUNDRED','HUNTING','HUSBAND','IMAGINE',
    'IMPROVE','INCLUDE','INDEXED','INITIAL','INSIGHT','INSPECT','INSTALL','INSTANT','INSTEAD',
    'INTEGER','INTENSE','INTERIM','INVOLVE','ISOLATE','JACKPOT','JOURNAL','JOURNEY','JUSTIFY',
    'KEEPING','KINGDOM','KITCHEN','LANDING','LARGELY','LASTING','LATERAL','LEADING','LEARNED',
    'LEATHER','LEAVING','LECTURE','LENDING','LIBERAL','LIBERTY','LIBRARY','LICENSE','LIMITED',
    'LINKING','LITERAL','LOCALLY','LOCATED','LOGICAL','LOTTERY','LOYALTY','LUGGAGE','MACHINE',
    'MAILING','MANAGER','MANDATE','MAPPING','MARTIAL','MASSAGE','MASSIVE','MASTERY','MEANING',
    'MEASURE','MEDICAL','MEETING','MENTION','MESSAGE','METHODS','MIGRATE','MILLION','MINERAL',
    'MINIMUM','MIRACLE','MISSION','MISTAKE','MIXTURE','MONITOR','MONTHLY','MOUNTED','MYSTERY',
    'NATURAL','NEAREST','NEGLECT','NEITHER','NETWORK','NEUTRAL','NOTABLE','NOTHING','NUCLEAR',
    'NURSERY','OBESITY','OBSCURE','OBSERVE','OBVIOUS','OFFENSE','OFFICER','ONGOING','OPENING',
    'OPERATE','OPINION','ORGANIC','OUTLINE','OUTLOOK','OUTSIDE','OVERALL','OVERLAP','PACKAGE',
    'PAINTER','PARKING','PARTIAL','PARTNER','PASSAGE','PASSING','PASSION','PASSIVE','PATIENT',
    'PATTERN','PAYMENT','PENALTY','PENDING','PENSION','PERFECT','PERHAPS','PERSIST','PHYSICS',
    'PICTURE','PIONEER','PIVOTAL','PLACING','PLANNED','PLASTIC','PLAYFUL','PLEASED','PODCAST',
    'POINTED','POPULAR','PORTION','PORTRAY','POVERTY','PRECISE','PREDICT','PREMIER','PREMIUM',
    'PREPARE','PRESENT','PRIMARY','PRINTER','PRIVACY','PRIVATE','PROBLEM','PROCEED','PROCESS',
    'PRODUCE','PRODUCT','PROFILE','PROGRAM','PROJECT','PROMISE','PROMOTE','PROTECT','PROTEIN',
    'PROTEST','PROVIDE','PUBLISH','PURPOSE','QUARTER','QUICKLY','RADICAL','RANKING','REALITY',
    'REBUILD','RECEIPT','RECEIVE','RECOVER','RECRUIT','REFLECT','REFUGEE','REGULAR','RELATED',
    'RELEASE','REMAINS','REMOVAL','RENEWED','REPLACE','REQUEST','REQUIRE','RESERVE','RESOLVE',
    'RESPECT','RESPOND','RESTORE','RETIRED','REVERSE','REVIVAL','ROUTINE','ROYALTY','RUNNING',
    'SATISFY','SAVINGS','SCATTER','SCHOLAR','SCORING','SECTION','SEEKING','SEGMENT','SERIOUS',
    'SESSION','SETTING','SEVENTH','SEVERAL','SHELTER','SHIFTED','SHORTLY','SIBLING','SKILLED',
    'SMOKING','SOLDIER','SOMEHOW','SPEAKER','SPECIAL','SPECIFY','SPONSOR','SQUEEZE','STADIUM',
    'STATION','STEALTH','STOMACH','STORAGE','STRANGE','STRETCH','STUDENT','STUMBLE','SUBJECT',
    'SUCCESS','SUGGEST','SUMMARY','SUPREME','SURGEON','SURPLUS','SURVIVE','SUSPECT','SUSPEND',
    'SUSTAIN','SYMPTOM','TACTICS','SUPPORT','SURFACE','THERMAL','THERAPY','THOUGHT','THUNDER',
    'TOBACCO','TONIGHT','TOPICAL','TOURISM','TOURIST','TOWARDS','TRACKER','TRADING','TRAFFIC',
    'TRANSIT','TRIGGER','TRIUMPH','TROUBLE','TRUSTED','TURNING','TYPICAL','UNCLEAR','UNHAPPY',
    'UNIFORM','UNKNOWN','UPDATED','UPGRADE','UTILITY','VACCINE','VARIETY','VARIOUS','VEHICLE',
    'VENTURE','VERSION','VETERAN','VIBRANT','VICTORY','VILLAGE','VINTAGE','VIOLENT','VIRTUAL',
    'VISIBLE','WARNING','WARRIOR','WASHING','WEATHER','WEBSITE','WEDDING','WEEKEND','WELCOME',
    'WELFARE','WESTERN','WILLING','WINNING','WITHOUT','WITNESS','WORKING','WRITING','WRITTEN',
    'YOUNGER'
  ],
  8: [
    'ABSOLUTE','ABSTRACT','ACADEMIC','ACCEPTED','ACCIDENT','ACCURATE','ACHIEVED','ACTUALLY',
    'ADDITION','ADEQUATE','ADJUSTED','ADVANCED','ADVOCATE','AFFECTED','AFFORDED','ALLIANCE',
    'ALTHOUGH','AMBITION','ANALYSIS','ANIMATED','ANNUALLY','ANYTHING','ANYWHERE','APPARENT',
    'APPENDIX','APPETITE','APPROACH','APPROVAL','ARRESTED','ARTISTIC','ASSEMBLY','ASSESSED',
    'ASSUMING','ATTACHED','ATTITUDE','AUDIENCE','AVIATION','BACKBONE','BACHELOR','BACKWARD',
    'BACTERIA','BALANCED','BANKRUPT','BASEBALL','BASEMENT','BATHROOM','BECOMING','BEHAVIOR',
    'BELIEVED','BIRTHDAY','BLESSING','BLOCKING','BORROWED','BOUNDARY','BREAKING','BREEDING',
    'BRINGING','BROADWAY','BROWSING','BUILDING','BULLETIN','BUSINESS','CALENDAR','CAMPAIGN',
    'CAPACITY','CASUALTY','CAUTIOUS','CEREMONY','CHAIRMAN','CHAMPION','CHANGING','CHARGING',
    'CHEERFUL','CHEMICAL','CHILDREN','CHOOSING','CIRCULAR','CLIMBING','CLINICAL','CLOTHING',
    'COACHING','COLLAPSE','COLONIAL','COLORFUL','COMBINED','COMEBACK','COMEDIAN','COMMERCE',
    'COMMONLY','COMMUNAL','COMPARED','COMPILER','COMPLAIN','COMPLETE','COMPOSED','COMPOUND',
    'COMPUTER','CONCLUDE','CONCRETE','CONFLICT','CONFUSED','CONGRESS','CONQUEST','CONSIDER',
    'CONSISTS','CONSTANT','CONSUMER','CONTINUE','CONTRACT','CONTRAST','CONVINCE','COOKBOOK',
    'CORRIDOR','COUNTING','COVERAGE','CREATIVE','CREATURE','CRIMINAL','CRITICAL','CROSSING',
    'CULTURAL','CURRENCY','CUSTOMER','DATABASE','DAUGHTER','DEADLINE','DECEMBER','DECISION',
    'DECLARED','DECLINED','DECREASE','DEFENDER','DEFINITE','DELICATE','DELIVERY','DESIGNED',
    'DESIGNER','DETAILED','DIABETES','DIALOGUE','DIPLOMAT','DIRECTED','DIRECTOR','DISABLED',
    'DISCOUNT','DISCOVER','DISCRETE','DISORDER','DISPATCH','DISPOSAL','DISTINCT','DISTRICT',
    'DIVIDEND','DIVISION','DOCTRINE','DOCUMENT','DOMESTIC','DOMINANT','DOWNLOAD','DOWNTOWN',
    'DRAMATIC','DRAWINGS','DRINKING','DROPPING','DURATION','DYNAMICS','EARNINGS','ECONOMIC',
    'EDUCATED','EIGHTEEN','ELECTION','ELECTRIC','ELIGIBLE','EMBEDDED','EMERGING','EMISSION',
    'EMPHASIS','EMPLOYED','EMPLOYEE','EMPLOYER','ENCLOSED','ENORMOUS','ENROLLED','ENTERING',
    'ENTIRELY','ENTITLED','ENTRANCE','ENVELOPE','EQUALITY','EQUIPPED','ESTIMATE','EVALUATE',
    'EVENTUAL','EVIDENCE','EVERYDAY','EVERYONE','EXCHANGE','EXCITING','EXCLUDED','EXERCISE',
    'EXISTING','EXPANDED','EXPECTED','EXPENSES','EXPLICIT','EXPLORER','EXPONENT','EXPORTED',
    'EXPOSURE','EXTENDED','EXTERNAL','FABULOUS','FACILITY','FAMILIAR','FAVORITE','FEATURED',
    'FEBRUARY','FEEDBACK','FEMININE','FESTIVAL','FIGURINE','FILENAME','FINALIST','FINALIZE',
    'FINANCED','FINISHED','FIREWALL','FLAGSHIP','FLEXIBLE','FLOATING','FOLLOWED','FOOTBALL',
    'FOOTWEAR','FORCEFUL','FORECAST','FORGIVEN','FORMALLY','FORMERLY','FORWARDS','FRAGMENT',
    'FRANKLIN','FREEZING','FREQUENT','FRIENDLY','FRONTIER','FRUITFUL','FUNCTION','GAMBLING',
    'GATHERED','GENERATE','GENEROUS','GLORIOUS','GLOSSARY','GOODNESS','GOVERNOR','GRACEFUL',
    'GRADIENT','GRADUATE','GRAPHICS','GRATEFUL','GRIPPING','GUARDIAN','GUIDANCE','HABITUAL',
    'HANDLING','HAPPENED','HARMLESS','HEADLINE','HELPLESS','HERITAGE','HOMEPAGE','HOMELESS',
    'HOMEWORK','HONESTLY','HONORARY','HORRIBLE','HOSPITAL','HUMANITY','HUMILITY','HYDROGEN',
    'IDENTIFY','IDENTITY','IDEOLOGY','IGNORANT','IMAGINED','IMMORTAL','IMPERIAL','IMPLICIT',
    'IMPORTED','IMPOSING','IMPROVED','INCIDENT','INCLUDED','INCREASE','INDICATE','INDIRECT',
    'INDUSTRY','INFERIOR','INFINITE','INFORMED','INHERENT','INITIATE','INNOCENT','INSTANCE',
    'INTEGRAL','INTENDED','INTERACT','INTEREST','INTERIOR','INTERNAL','INTERVAL','INTIMATE',
    'INVASION','INVENTOR','INVESTED','INVESTOR','INVOLVED','ISOLATED','JUDGMENT','JUNCTION',
    'KEYBOARD','KNOCKING','KNOCKOUT','LANDMARK','LANGUAGE','LAUGHING','LAUNCHED','LEARNING',
    'LIFETIME','LIGHTING','LIMITING','LITERARY','LOCATION','LOGISTIC','MAINTAIN','MAJORITY',
    'MANAGING','MANIFEST','MANUALLY','MARATHON','MARGINAL','MARRIAGE','MATERIAL','MATURITY',
    'MAXIMIZE','MECHANIC','MEDICINE','MEDIEVAL','MEMORIAL','MERCHANT','METADATA','MIDNIGHT',
    'MILITANT','MILITARY','MINIMIZE','MINISTER','MINORITY','MODERATE','MOMENTUM','MONETARY',
    'MORTGAGE','MOUNTING','MOVEMENT','MULTIPLY','MUTATION','NATIONAL','NAVIGATE','NEGATIVE',
    'NEIGHBOR','NINETEEN','NOMINATE','NORMALLY','NORTHERN','NOTEBOOK','NOVEMBER','NUMEROUS',
    'OBSERVED','OBSERVER','OBSOLETE','OBSTACLE','OBTAINED','OCCASION','OCCUPIED','OCCURRED',
    'OFFERING','OFFICIAL','OFFSHORE','OPERATOR','OPPONENT','OPPOSITE','OPTIMIZE','OPTIONAL',
    'ORDINARY','ORGANIZE','ORIGINAL','OVERCOME','OVERHEAD','OVERLOOK','OVERTIME','OVERVIEW',
    'PAINTING','PAMPHLET','PARALLEL','PARENTAL','PARTISAN','PASSPORT','PASSWORD','PATIENCE',
    'PEACEFUL','PERCEIVE','PERIODIC','PERSONAL','PERSUADE','PETITION','PHYSICAL','PIPELINE',
    'PLATFORM','PLEASANT','PLEASURE','POINTING','POLICING','POLISHED','POPULACE','PORTABLE',
    'PORTRAIT','POSITIVE','POSSIBLY','POWERFUL','PRACTICE','PRECIOUS','PREGNANT','PREMIERE',
    'PREPARED','PRESERVE','PRESSURE','PRESUMED','PREVIOUS','PRIORITY','PROBABLE','PROBABLY',
    'PROCEEDS','PRODUCED','PRODUCER','PROFOUND','PROGRESS','PROHIBIT','PROLIFIC','PROMPTED',
    'PROPERLY','PROPERTY','PROPOSAL','PROPOSED','PROSPECT','PROTOCOL','PROVIDED','PROVIDER',
    'PROVINCE','PUBLICLY','PURCHASE','PUZZLING','QUANTITY','QUARTERS','QUESTION','RANDOMLY',
    'RATIONAL','READABLE','REACTION','REASONED','RECEIVED','RECENTLY','RECORDED','RECOVERY',
    'REDESIGN','REDUCING','REFERRAL','REFLECTS','REFORMED','REGIONAL','REGISTER','REGULATE',
    'RELEASED','RELEVANT','REMEMBER','REMOVING','RENOWNED','REPEATED','REPLACED','REPORTED',
    'REPORTER','REQUIRED','RESEARCH','RESERVED','RESIDENT','RESIGNED','RESOLVED','RESOURCE',
    'RESPONSE','RESTORED','RESTRAIN','RESTRICT','RETAILER','RETAINED','RETIRING','REVEALED',
    'REVERSAL','REVIEWED','REVISION','ROMANTIC','SANDWICH','SATURDAY','SCENARIO','SCHEDULE',
    'SCIENCES','SCRUTINY','SEASONAL','SECONDLY','SECRETLY','SECURING','SECURITY','SELECTED',
    'SEMESTER','SEPARATE','SEQUENCE','SERGEANT','SETTINGS','SEVERITY','SHIFTING','SHIPPING',
    'SHOCKING','SHOPPING','SHORTAGE','SHOULDER','SHUTDOWN','SIDELINE','SIGNALED','SILENTLY',
    'SIMPLIFY','SIMULATE','SINGULAR','SITUATED','SKELETON','SLIGHTLY','SMOOTHLY','SNOWFALL',
    'SOFTWARE','SOLUTION','SOMEBODY','SOMETIME','SOMEWHAT','SOUTHERN','SPACIOUS','SPEAKING',
    'SPECIFIC','SPENDING','SPINNING','SPLENDID','SPORTING','SQUARELY','STAFFING','STANDARD',
    'STANDING','STARTING','STATIONS','STEADILY','STEERING','STEPPING','STIMULUS','STOPPING',
    'STRAIGHT','STRANGER','STRATEGY','STRENGTH','STRESSED','STRICKEN','STRIKING','STRONGLY',
    'STRUGGLE','STUDYING','STUNNING','SUBURBAN','SUDDENLY','SUFFERED','SUITABLE','SUPERIOR',
    'SUPPLIED','SUPPLIER','SUPPOSED','SUPPRESS','SURGICAL','SURPRISE','SURROUND','SURVIVAL',
    'SURVIVED','SURVIVOR','SUSPENSE','SWIMMING','SYMBOLIC','SYMPATHY','SYNDROME','TARGETED',
    'TEACHING','TENDENCY','TERMINAL','THINKING','THIRTEEN','THOROUGH','THOUSAND','THRILLER',
    'TIMELINE','TOGETHER','TOLERANT','TOMORROW','TORTOISE','TOUCHING','TOWNSHIP','TRACKING',
    'TRAILING','TRAINING','TRANSFER','TRANSMIT','TREASURE','TRIBUNAL','TRILLION','TROPICAL',
    'TROUBLED','TRUSTEES','TUTORIAL','ULTIMATE','UMBRELLA','UNCOMMON','UNDERWAY','UNIVERSE',
    'UNLIKELY','UNLOCKED','UPDATING','UPSTREAM','USERNAME','VACATION','VALIDATE','VALUABLE',
    'VARIABLE','VELOCITY','VERIFIED','VERTICAL','VETERANS','VIOLENCE','VIRTUOUS','VOLATILE',
    'WHENEVER','WHEREVER','WILDCARD','WILDLIFE','WIRELESS','WITHDRAW','WORKSHOP','YIELDING'
  ],
  9: [
    'ABANDONED','ABOLITION','ABUNDANCE','ACCORDING','ADVENTURE','AFTERNOON','AGREEMENT',
    'ALGORITHM','ALONGSIDE','ALLOCATED','ALLOWANCE','AMENDMENT','ANIMATION','ANNOUNCED',
    'ANONYMOUS','APARTMENT','APPLICANT','APPOINTED','ARBITRARY','ARCHITECT','AUTHORITY',
    'AUTOMATIC','BANDWIDTH','BEGINNING','BILLBOARD','BIOGRAPHY','BLUEPRINT','BOULEVARD',
    'BREAKFAST','BROADCAST','BUTTERFLY','CALCULATE','CANDIDATE','CATALOGUE','CELEBRATE',
    'CERTAINLY','CHALLENGE','CHARACTER','CHILDHOOD','CHOCOLATE','CHRONICLE','CLASSROOM',
    'COALITION','COLLEAGUE','COMMUNITY','COMPANION','COMPETING','COMPLAINT','COMPONENT',
    'COMPOSITE','CONCERNED','CONCLUDED','CONDITION','CONDUCTED','CONFESSED','CONFIDENT',
    'CONFIRMED','CONNECTED','CONQUERED','CONSCIOUS','CONSENSUS','CONSTRUCT','CONTACTED',
    'CONTAINED','CONTENDER','CONTINENT','CONTINUED','COOPERATE','CORPORATE','CORRECTED',
    'COURTYARD','CRAFTSMAN','CURRENTLY','CUSTOMIZE','DANGEROUS','DASHBOARD','DATABASES',
    'DEDICATED','DEFENDING','DELIVERED','DEMANDING','DEMOCRACY','DEPARTURE','DEPENDENT',
    'DEPOSITED','DESCRIBED','DETECTIVE','DETERMINE','DEVELOPED','DEVELOPER','DIAGNOSED',
    'DIMENSION','DIRECTION','DIRECTORY','DISAPPEAR','DISCHARGE','DISCLOSED','DISCOVERS',
    'DISCOVERY','DISCUSSED','DISMISSAL','DISPLACED','DISPLAYED','DISTANCES','DISTURBED',
    'DIVIDENDS','DOCUMENTS','DOMINATED','DUPLICATE','ECONOMICS','EDUCATION','EFFICIENT',
    'ELABORATE','ELIMINATE','EMERGENCY','EMOTIONAL','EMPHASIZE','ENCOUNTER','ENCOURAGE',
    'ENDURANCE','ENJOYABLE','ENJOYMENT','ENROLMENT','ENTERTAIN','EQUIPMENT','ESSENTIAL',
    'ESTABLISH','ESTIMATED','EVACUATED','EVALUATED','EVERYBODY','EVOLUTION','EXAMINING',
    'EXCELLENT','EXCEPTION','EXCESSIVE','EXCHANGED','EXCLUDING','EXCLUSIVE','EXECUTIVE',
    'EXEMPTION','EXERCISED','EXHAUSTED','EXISTENCE','EXPANDING','EXPANSION','EXPENSIVE',
    'EXPLAINED','EXPLOSION','EXPRESSED','EXTENDING','EXTENSION','EXTENSIVE','FABRICATE',
    'FACULTIES','FANTASTIC','FAVORABLE','FEATURING','FINANCIAL','FIREPLACE','FLOWERING',
    'FORBIDDEN','FORMATION','FRAGILITY','FRAMEWORK','FRANCHISE','FREQUENCY','FRONTLINE',
    'FULFILLED','FURNITURE','GARDENING','GENUINELY','GEOGRAPHY','GRADUALLY','GRADUATED',
    'GUARANTEE','GUERRILLA','GUIDELINE','GYMNASIUM','HAPPENING','HARMONIZE','HEARTBEAT',
    'HEARTFELT','HISTORIAN','HONEYMOON','HOPEFULLY','HORSEBACK','HOUSEHOLD','HURRICANE',
    'IDENTICAL','IMAGINARY','IMMEDIATE','IMMIGRANT','IMPLEMENT','IMPORTANT','IMPORTING',
    'IMPRESSED','INCLUDING','INCREASED','INDICATED','INDICATOR','INFECTION','INFLUENCE',
    'INITIALLY','INITIATED','INJECTION','INSPECTOR','INSTALLED','INSTANTLY','INSTITUTE',
    'INSURANCE','INTEGRATE','INTELLECT','INTENDING','INTENSITY','INTENSIVE','INTENTION',
    'INTERCEPT','INTERFACE','INTERPRET','INTERVALS','INTERVIEW','INTRODUCE','INVENTION',
    'INVISIBLE','INVOLVING','IRRITATED','ITINERARY','JEWELLERY','JUDGEMENT','JUSTIFIED',
    'KEYSTROKE','KIDNAPPED','KILOMETER','KNOWLEDGE','LANDSCAPE','LAUNCHING','LEGENDARY',
    'LETTERBOX','LIABILITY','LIBRARIAN','LICENSING','LIFESTYLE','LIGHTNING','LITERALLY',
    'LIVESTOCK','LOGISTICS','LONGEVITY','MAGNITUDE','MAINFRAME','MANDATORY','MANIFESTO',
    'MARKETING','MASSIVELY','MECHANISM','MEDICALLY','MENTIONED','MESSENGER','MILESTONE',
    'MINIATURE','MODERATOR','MOLECULAR','MOMENTOUS','MONITORED','MOTIVATED','MUNICIPAL',
    'NARRATIVE','NECESSARY','NEGLECTED','NEIGHBOUR','NIGHTMARE','NOMINATED','NONPROFIT',
    'NUTRITION','OBJECTION','OBJECTIVE','OBLIGATED','OBSERVING','OBSESSION','OCCURRING',
    'OFFENDING','OFFENSIVE','OFFICIALS','OPERATION','OPPONENTS','ORCHESTRA','ORGANIZER',
    'OTHERWISE','OURSELVES','OUTSPOKEN','OVERNIGHT','OWNERSHIP','PACKAGING','PARTIALLY',
    'PARTITION','PASSENGER','PATRONAGE','PENALTIES','PENINSULA','PERCEIVED','PERFECTLY',
    'PERFORMED','PERMANENT','PERMITTED','PERPETUAL','PETROLEUM','PLACEMENT','PLAINTIFF',
    'PLANETARY','POLITICAL','POPULATED','POSSESSED','POTENTIAL','POWERLESS','PRACTICAL',
    'PRECEDING','PRECISELY','PRECISION','PREDICTED','PREFERRED','PREJUDICE','PRESENTED',
    'PRESERVED','PRESIDENT','PRESSURED','PREVALENT','PREVENTED','PRIMARILY','PRIMITIVE',
    'PRINCIPAL','PRINCIPLE','PRIVILEGE','PROCEEDED','PROCESSOR','PRODUCERS','PRODUCING',
    'PROFESSED','PROFESSOR','PROFILING','PROGRAMME','PROJECTED','PROMINENT','PROMISING',
    'PROMOTION','PROPOSALS','PROPOSING','PROSECUTE','PROSPECTS','PROTECTED','PROVIDING',
    'PROVOKING','PUBLISHED','PUBLISHER','PURCHASED','QUALIFIED','QUARTERLY','RASPBERRY',
    'RATIONALE','REACTIONS','REASONING','RECEPTION','RECIPIENT','RECKONING','RECOGNIZE',
    'RECOMMEND','RECONCILE','RECOVERED','RECTANGLE','RECYCLING','REDUNDANT','REFERENCE',
    'REFLECTED','REFORMING','REGARDING','REGISTERS','REGULATED','REGULATOR','REINSTALL',
    'RELATIONS','RELEASING','RELEVANCE','RELUCTANT','REMAINDER','REMAINING','RENEWABLE',
    'REOPENING','REPORTING','REPRESENT','REPRODUCE','REPRODUCE','REQUESTED','REQUIRING',
    'RESEMBLED','RESERVOIR','RESIDENCE','RESISTANT','RESOLVING','RESONANCE','RESOURCES',
    'RESPECTED','RESPONDED','RESTORING','RESULTING','RETENTION','RETRIEVAL','RETURNING',
    'REVEALING','REVIEWING','REVOLVING','RIGHTEOUS','SAFEGUARD','SANCTUARY','SATELLITE',
    'SATISFIED','SCHEDULED','SCHOLARLY','SCIENTIST','SCREENING','SCULPTURE','SECRETARY',
    'SECONDARY','SELECTING','SELECTION','SENSITIVE','SEPARATED','SEPTEMBER','SEQUENCED',
    'SERIOUSLY','SEVENTEEN','SHATTERED','SHELTERED','SHORTCUTS','SHOULDERS','SIGNATURE',
    'SIMULATOR','SITUATION','SKEPTICAL','SOLUTIONS','SOMEWHERE','SOUTHEAST','SOUTHWEST',
    'SOVEREIGN','SPECIALTY','SPECIFIED','SPECTACLE','SPIRITUAL','SPLITTING','SPOTLIGHT',
    'SPREADING','STAIRCASE','STATEMENT','STATIONED','STEADFAST','STIMULATE','STRATEGIC',
    'STREAMING','STRETCHED','STRUCTURE','SUBSTANCE','SUCCEEDED','SUFFERING','SUGGESTED',
    'SUMMATION','SUPERVISE','SUPPLYING','SUPPORTER','SUPPOSING','SUPREMACY','SURPRISED',
    'SURRENDER','SURROUNDS','SURVIVING','SUSPECTED','SUSPENDED','SUSTAINED','SWITCHING',
    'SYMBOLIZE','SYMPOSIUM','TARGETING','TECHNIQUE','TELEPHONE','TELESCOPE','TEMPORARY',
    'TERRITORY','TERRORISM','TESTAMENT','THANKLESS','THEREFORE','THRESHOLD','TIGHTENED',
    'TIMESTAMP','TOLERANCE','TRADEMARK','TRADITION','TRANSPORT','TREATMENT','TREMBLING',
    'TRIGGERED','TRIUMPHED','TYPICALLY','UNANIMITY','UNCERTAIN','UNCOVERED','UNDERGONE',
    'UNDERLINE','UNDERMINE','UNDERTAKE','UNIVERSAL','UNLIMITED','UNRELATED','UPHOLDING',
    'VALENTINE','VARIATION','VEGETABLE','VIOLATION','VIRTUALLY','VOLUNTEER','WANDERING',
    'WAREHOUSE','WARRANTED','WELLBEING','WHOLESALE','WITHSTAND','WITNESSED','WONDERFUL',
    'WRESTLING','YESTERDAY'
  ],
  10: [
    'ABSOLUTELY','ACCESSIBLE','ACCOMPLISH','ACCOUNTANT','ACCOUNTING','ACCUSATION','ADAPTATION',
    'AMBASSADOR','APPARENTLY','APPEARANCE','APPLICABLE','APPRECIATE','ASSUMPTION','ATTENDANCE',
    'ATTRACTION','BACKGROUND','BASKETBALL','BOUNDARIES','BREAKPOINT','BRIGHTNESS','CALCULATOR',
    'CAPITALIZE','CENTENNIAL','CHANCELLOR','CHANGEABLE','CHECKPOINT','COLLECTIVE','COMMISSION',
    'COMMITMENT','COMPARISON','COMPATIBLE','COMPELLING','COMPENSATE','COMPETENCE','COMPLETELY',
    'COMPLIANCE','COMPROMISE','CONCEPTION','CONCLUSION','CONDITIONS','CONFERENCE','CONFIDENCE',
    'CONNECTION','CONSCIENCE','CONSEQUENT','CONSIDERED','CONSISTENT','CONSPIRACY','CONSULTANT',
    'CONTRIBUTE','CONTROLLER','CONVENIENT','CONVENTION','CONVICTION','COORDINATE','CORRESPOND',
    'COUNCILLOR','COURAGEOUS','CREATIVITY','CURRICULUM','DECORATING','DECORATION','DEFICIENCY',
    'DEFINITELY','DEFINITION','DELIVERING','DEPARTMENT','DEPENDABLE','DEPLOYMENT','DEPRESSION',
    'DESCENDING','DESIGNATED','DETERMINED','DEVELOPING','DICTIONARY','DIMENSIONS','DISABILITY',
    'DISCLAIMER','DISCONNECT','DISCOURAGE','DISCOVERED','DISCUSSION','DISTRIBUTE','DISTORTION',
    'DOMINATION','DOWNSTREAM','EARTHQUAKE','EFFICIENCY','ELECTRONIC','ELEMENTARY','EMIGRATING',
    'EMPLOYMENT','ENDANGERED','ENGAGEMENT','ENTERPRISE','ENTHUSIASM','EVENTUALLY','EVERYTHING',
    'EXCELLENCE','EXHIBITION','EXPEDITION','EXPERIENCE','EXPERIMENT','EXPLICITLY','EXPRESSION',
    'EXTRACTION','FACILITATE','FEDERATION','FLASHLIGHT','FOOTBALLER','FOUNDATION','FRANCHISES',
    'FRIENDSHIP','GENERATING','GENERATION','GRADUATION','GUARANTEED','GUIDELINES','GYMNASTICS',
    'HARASSMENT','HARVESTING','HEALTHCARE','HESITATION','HIGHLIGHTS','HORIZONTAL','HYPOTHESIS',
    'IDENTIFIED','ILLUMINATE','ILLUSTRATE','IMMIGRANTS','IMPRESSION','INADEQUATE','INAUGURATE',
    'INCOMPLETE','INCREDIBLE','INDICATION','INDIVIDUAL','INFLUENCES','INITIATION','INNOVATION',
    'INNOVATIVE','INSPECTING','INSPECTION','INSTALLING','INSTRUMENT','INTEGRATED','INTERESTED',
    'INTRODUCED','INVESTMENT','IRRELEVANT','JOURNALISM','JOURNALIST','LEADERSHIP','LEGITIMATE',
    'LIMITATION','LITERATURE','MAGISTRATE','MAINSTREAM','MANAGEMENT','MEANINGFUL','MECHANICAL',
    'MEMBERSHIP','MISCONDUCT','MODERATELY','MOTORCYCLE','MULTIMEDIA','NATIONWIDE','NAVIGATION',
    'NEWSLETTER','NOMINATION','OBLIGATION','OCCUPATION','OPPOSITION','ORIGINALLY','OUTPERFORM',
    'PAINTBRUSH','PARTICULAR','PEACEFULLY','PERCENTAGE','PERFORMING','PERMISSION','PERSISTENT',
    'PERSONALLY','PERSUASION','PHENOMENON','PHILOSOPHY','PHOTOGRAPH','PLANTATION','PLAYGROUND',
    'POSITIONED','POSSESSION','POWERFULLY','PREFERENCE','PRESIDENCY','PRESUMABLY','PREVENTION',
    'PREVIOUSLY','PROCEEDING','PROCESSING','PROFESSION','PROFITABLE','PROGRAMMER','PROHIBITED',
    'PROJECTION','PROMINENCE','PRONOUNCED','PROPORTION','PROSECUTOR','PROSPERITY','PROTECTION',
    'PUBLISHING','PUNISHMENT','QUARANTINE','REASONABLE','REBUILDING','RECREATION','REGARDLESS',
    'REGRESSION','REGULATION','RELATIVELY','RELAXATION','REMARKABLY','REPEATEDLY','REPOSITORY',
    'REPUBLICAN','REPUTATION','RESEARCHER','RESEMBLING','RESENTMENT','RESOLUTION','RESTAURANT',
    'RETIREMENT','REVELATION','REVOLUTION','RIDICULOUS','SCREENPLAY','SETTLEMENT','SIMPLIFIED',
    'SIMULATION','SKATEBOARD','SMARTPHONE','SOLIDARITY','SPECIALIST','SPECIALIZE','STANDPOINT',
    'STATIONARY','STRENGTHEN','STRUCTURED','SUBSEQUENT','SUBSTITUTE','SUCCEEDING','SUGGESTION',
    'SUPPLEMENT','SUPPOSEDLY','SURPRISING','SURROUNDED','SUSPICIOUS','TECHNOLOGY','TELEVISION',
    'THEMSELVES','THEREAFTER','THOUGHTFUL','THREATENED','THROUGHOUT','TOURNAMENT','TRANSPLANT',
    'TREMENDOUS','ULTIMATELY','UNDERSTAND','UNEMPLOYED','UNEXPECTED','UNOFFICIAL','UNRELIABLE',
    'VOLLEYBALL','VULNERABLE','WHEELCHAIR','WIDESPREAD','WITHDRAWAL','YOURSELVES'
  ]
};

// Seeded random number generator for reproducible puzzles
export class SeededRandom {
  constructor(seed) {
    this.seed = seed;
  }

  next() {
    this.seed = (this.seed * 16807 + 0) % 2147483647;
    return (this.seed - 1) / 2147483646;
  }

  nextInt(min, max) {
    return Math.floor(this.next() * (max - min + 1)) + min;
  }

  shuffle(arr) {
    const result = [...arr];
    for (let i = result.length - 1; i > 0; i--) {
      const j = this.nextInt(0, i);
      [result[i], result[j]] = [result[j], result[i]];
    }
    return result;
  }
}

// Generate words and initial cube state for a puzzle
export function generatePuzzle(cubeSize, seed = null) {
  if (!seed) seed = Date.now() % 2147483647;
  const rng = new SeededRandom(seed);

  // Determine number of words based on cube size
  const numWords = Math.min(cubeSize + 2, 12);

  // Collect eligible words (length <= cubeSize)
  let eligibleWords = [];
  for (let len = 3; len <= cubeSize; len++) {
    if (WORD_BANK[len]) {
      eligibleWords = eligibleWords.concat(WORD_BANK[len]);
    }
  }
  eligibleWords = rng.shuffle(eligibleWords);

  // Select words ensuring no duplicates and good distribution of lengths
  const selectedWords = [];
  const usedLetterPositions = new Set();

  for (const word of eligibleWords) {
    if (selectedWords.length >= numWords) break;
    // Avoid very similar words
    const isDuplicate = selectedWords.some(w =>
      w === word || w.includes(word) || word.includes(w)
    );
    if (!isDuplicate) {
      selectedWords.push(word);
    }
  }

  // Create initial (solved) face state: 6 faces, each NxN
  const FACES = 6;
  const faces = [];
  for (let f = 0; f < FACES; f++) {
    faces[f] = [];
    for (let r = 0; r < cubeSize; r++) {
      faces[f][r] = [];
      for (let c = 0; c < cubeSize; c++) {
        faces[f][r][c] = '';
      }
    }
  }

  // Place words on faces
  const wordPlacements = [];
  for (const word of selectedWords) {
    let placed = false;
    let attempts = 0;

    while (!placed && attempts < 100) {
      attempts++;
      const face = rng.nextInt(0, FACES - 1);
      const horizontal = rng.next() > 0.5;

      if (horizontal) {
        if (word.length > cubeSize) continue;
        const row = rng.nextInt(0, cubeSize - 1);
        const col = rng.nextInt(0, cubeSize - word.length);

        // Check if space is free
        let free = true;
        for (let i = 0; i < word.length; i++) {
          const key = `${face}-${row}-${col + i}`;
          if (usedLetterPositions.has(key)) { free = false; break; }
        }

        if (free) {
          for (let i = 0; i < word.length; i++) {
            faces[face][row][col + i] = word[i];
            usedLetterPositions.add(`${face}-${row}-${col + i}`);
          }
          wordPlacements.push({
            word, face, row, col, horizontal: true, length: word.length
          });
          placed = true;
        }
      } else {
        if (word.length > cubeSize) continue;
        const row = rng.nextInt(0, cubeSize - word.length);
        const col = rng.nextInt(0, cubeSize - 1);

        let free = true;
        for (let i = 0; i < word.length; i++) {
          const key = `${face}-${row + i}-${col}`;
          if (usedLetterPositions.has(key)) { free = false; break; }
        }

        if (free) {
          for (let i = 0; i < word.length; i++) {
            faces[face][row + i][col] = word[i];
            usedLetterPositions.add(`${face}-${row + i}-${col}`);
          }
          wordPlacements.push({
            word, face, row, col, horizontal: false, length: word.length
          });
          placed = true;
        }
      }
    }
  }

  // Fill remaining cells with random letters
  const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  for (let f = 0; f < FACES; f++) {
    for (let r = 0; r < cubeSize; r++) {
      for (let c = 0; c < cubeSize; c++) {
        if (!faces[f][r][c]) {
          faces[f][r][c] = ALPHABET[rng.nextInt(0, 25)];
        }
      }
    }
  }

  // Generate scramble moves
  const scrambleMoveCount = cubeSize * 4 + rng.nextInt(5, 15);
  const scrambleMoves = [];
  for (let i = 0; i < scrambleMoveCount; i++) {
    scrambleMoves.push({
      axis: rng.nextInt(0, 2),       // 0=x, 1=y, 2=z
      layer: rng.nextInt(0, cubeSize - 1),
      direction: rng.next() > 0.5 ? 1 : -1  // clockwise or counter-clockwise
    });
  }

  // Return only the placed words
  const targetWords = wordPlacements.map(p => p.word);

  return {
    seed,
    cubeSize,
    solvedFaces: faces,
    targetWords,
    wordPlacements,
    scrambleMoves
  };
}

// Check if target words exist on the current face grids
export function findWordsOnFaces(faceGrids, targetWords, cubeSize) {
  const foundWords = new Map(); // word -> [{face, positions:[{row,col}...]}]

  for (const word of targetWords) {
    const locations = [];

    for (let f = 0; f < 6; f++) {
      const grid = faceGrids[f];

      // Check rows (left to right)
      for (let r = 0; r < cubeSize; r++) {
        const rowStr = grid[r].join('');
        let idx = rowStr.indexOf(word);
        while (idx !== -1) {
          const positions = [];
          for (let i = 0; i < word.length; i++) {
            positions.push({ row: r, col: idx + i });
          }
          locations.push({ face: f, positions, direction: 'row' });
          idx = rowStr.indexOf(word, idx + 1);
        }
        // Check reversed
        const revStr = rowStr.split('').reverse().join('');
        idx = revStr.indexOf(word);
        while (idx !== -1) {
          const positions = [];
          for (let i = 0; i < word.length; i++) {
            positions.push({ row: r, col: cubeSize - 1 - (idx + i) });
          }
          locations.push({ face: f, positions, direction: 'row-rev' });
          idx = revStr.indexOf(word, idx + 1);
        }
      }

      // Check columns (top to bottom)
      for (let c = 0; c < cubeSize; c++) {
        let colStr = '';
        for (let r = 0; r < cubeSize; r++) colStr += grid[r][c];

        let idx = colStr.indexOf(word);
        while (idx !== -1) {
          const positions = [];
          for (let i = 0; i < word.length; i++) {
            positions.push({ row: idx + i, col: c });
          }
          locations.push({ face: f, positions, direction: 'col' });
          idx = colStr.indexOf(word, idx + 1);
        }
        // Check reversed
        const revStr = colStr.split('').reverse().join('');
        idx = revStr.indexOf(word);
        while (idx !== -1) {
          const positions = [];
          for (let i = 0; i < word.length; i++) {
            positions.push({ row: cubeSize - 1 - (idx + i), col: c });
          }
          locations.push({ face: f, positions, direction: 'col-rev' });
          idx = revStr.indexOf(word, idx + 1);
        }
      }
    }

    foundWords.set(word, locations);
  }

  return foundWords;
}
